version: 2.1


commands:
  install_system_dependencies:
    description: "Install system-level libraries/tools we depend on"
    steps:
      - run:
          name: Install system dependencies
          command: |
            case "$(uname -s)" in
              Linux*)
                apt --quiet update
                apt --yes install libgexiv2-dev
                ;;
              Darwin*)
                brew install gexiv2 pkg-config
                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
                ;;
            esac
  build_and_test_steps:
    description: "Build the library and test it"
    steps:
      - checkout
      - install_system_dependencies
      - run:
          name: Show environment info
          command: |
            rustc --version --verbose && echo ""
            cargo --version --verbose && echo ""
            case "$(uname -s)" in
              Linux*)
                dpkg --list libgexiv2-dev libexiv2-dev ;;
              Darwin*)
                brew list --versions gexiv2 exiv2 ;;
            esac
      - run:
          name: Build
          command: cargo build --verbose --all-features
      - run:
          name: Test
          command: cargo test --verbose --all-features
      - run:
          name: Run Examples
          command: |
            cargo run --example gps
            cargo run --example timestamp


linux_job_config: &linux_job_config
  resource_class: small
  steps:
    - build_and_test_steps


jobs:
  test-linux-msrv:
    docker:
      - image: rust:1.56-slim
    <<: *linux_job_config
  test-linux-stable:
    docker:
      - image: rust:slim
    <<: *linux_job_config
  test-linux-nightly:
    docker:
      - image: rustlang/rust:nightly-slim
    <<: *linux_job_config
  test-osx-stable:
    macos:
      xcode: "14.0.0"
    steps:
      - build_and_test_steps
  lint-and-format:
    docker:
      - image: rustlang/rust:nightly-slim
    steps:
      - checkout
      - install_system_dependencies
      - run:
          name: Run linter
          command: cargo +nightly clippy
      - run:
          name: Check formatting
          command: cargo +nightly fmt --check


workflows:
  build-and-test:
    jobs:
      - test-linux-msrv
      - test-linux-stable
      - test-linux-nightly
      - test-osx-stable
      - lint-and-format
